version: '3'
services:
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=robin.r dbname=people sslmode=disable timezone=UTC connect_timeout=5"
  postgres:
    image: 'postgres:12'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: robin.r
      POSTGRES_PASSWORD: 
      POSTGRES_DB: people
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/